config/routes.rb
Rails.application.routes.draw do
  resources :comments
  root 'projects#index'
  
  resources :projects
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ProjectEvent

	validates_length_of :comment, :maximum => 255, :message => "less than %d if you don't mind"
end

app/models/history.rb
class History < ProjectEvent

end

app/models/project.rb
class Project < ApplicationRecord
	has_many :project_events
	has_many :comments
	has_many :histories

	before_save :record_changes

  enum status: {
    pending: 1,
    active: 2,
    completed: 3
  }


  def record_changes
  	return true unless changed?

  	history = changes
  	history = self.histories.build
  	history.user_name = 'johnny doe'
  	history.data_changes = changes
  end
end

app/models/project_event.rb
class ProjectEvent < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @project_id = params[:project_id]
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    @project = @comment.project


    respond_to do |format|
      if @comment.save
        format.html { redirect_to project_url(@project), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:comment, :user_name, :project_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:project_id_id, :comment, :changes, :type)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name %>
  </div>

  <div class="field">
    <%= form.hidden_field :project_id, value: @project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Author</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.author %></td>
        <td><%= comment.project_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Project:</strong>
  <%= @comment.project_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeyTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <main class="container mx-auto mt-28 px-5 flex">
      <div class="p-5 h-screen w-full ">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<div class="bg-gray-50 p-8">
  <%= form_with(model: project, local: true) do |form| %>
    <% if project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
          <% project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'w-full rounded ' %>
    </div>

    <br>
    <br>

    <div class="field">
      <%= form.label :status %> <br>
      <%= form.select :status, :collection => Project.statuses.keys.to_a %>
    </div>

    <br>
    <br>

    <div class="actions">
      <%= form.submit 'Save', class: 'btn bg-green-100' %>
    </div>
  <% end %>
</div>

app/views/projects/_project_events.html.erb
<div>
  <h2><u>History</u></h2> <br>
  <% @project.project_events.each do |event| %>

    <% if event.is_a?(Comment) %>
      <div class="bg-pink-100 rounded-md p-3 mb-8">
        <h5><u>Comments</u></h5>
        <h5><i>Author</i>: <%= event.user_name %></h5>
        <h5><%= event.created_at.strftime("%d/%m/%Y %H:%M") %></h5>

        <p><%= event.comment %></p>
      </div>
    <% else %>
      <div class="bg-red-100 rounded-md p-3 mb-8">
        <h5><u>Changes</u></h5>
        <h5><i>Author</i>: <%= event.user_name %></h5>
        <h5><%= event.created_at.strftime("%d/%m/%Y %H:%M") %></h5>

        <% event.data_changes && event.data_changes.each do |key, values| %>
          <p><span>Previous <%= key %>:</span> <b><%= values[0] %></b></p>
          <p><span>Changed to <%= key %>:</span> <b><%= values[1] %></b></p>
        <% end %>

      </div>
    <% end %>
  <% end %>

  <br>
  <br>

  <%= link_to 'Add New Comment', new_comment_path(project_id: @project.id),  class: 'btn bg-green-400' %>

</div>

app/views/projects/_state_history.html.erb
<div>
  <h2><u>History of State changes</u></h2>
  <% @project.versions.each do |v| %>

		<% if v.changeset['state'].present? %>
		  <div style=" border: 1px; border-radius: 10px; background: lightyellow; margin-bottom: 20px; padding: 10px;">
		    <h5><i>Changed at</i>: <%= v.changeset['updated_at'][1].to_time.strftime( "%H:%M  %d/%m/%Y") %></h5>

		    <p><span>Previous state:</span> <b><%= v.changeset['state'][0] %></b></p>
		    <p><span>Changed to state:</span> <b><%= v.changeset['state'][1] %></b></p>
		  </div>
		<% end %>
	<% end %>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<br>
<br>
<br>
<%= link_to 'Show', @project, class: 'btn bg-gray-100' %> |
<%= link_to 'Back', projects_path, class: 'btn bg-blue-100' %>
<br>
<br>
<br>

app/views/projects/index.html.erb
  <div>
    <p id="notice"><%= notice %></p>
    <h1 class="text-xl- mb-2">Projects</h1> <br>

    <table class="w-full">
      <thead class="bg-gray-800 text-white">
        <tr>
          <th>Name</th>
          <th>State</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @projects.each_with_index do |project, index| %>
          <tr class= <%= index.odd? ? 'bg-gray-50' : 'bg-white' %> >
            <td class='p-3 text-sm font-semibold text-gray-700'><%= project.name %></td>
            <td class='p-3 text-sm font-semibold text-gray-700'><%= project.status %></td>
            <td class='p-3 text-sm font-semibold text-gray-700'><%= link_to 'Show', project_path(project), class: 'btn bg-blue-200' %></td>
            <td class='p-3 text-sm font-semibold text-gray-700'><%= link_to 'Edit', edit_project_path(project), class: 'btn bg-gray-200' %></td>
            <td class='p-3 text-sm font-semibold text-gray-700'><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn bg-red-200' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Project', new_project_path, class: 'btn bg-blue-200' %>
  </div>  

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @project.status %>
</p>

<br>
<br>

<%= render('project_events') %>

<br>
<br>

<%= link_to 'Edit project', edit_project_path(@project),  class: 'btn bg-gray-100 mt-8' %> |
<%= link_to 'Back to projects', projects_path,  class: 'btn bg-blue-100 mb-8' %>